Hacker.delete_all

h1 = Hacker.create({ address: '32 Bowling Green Lane, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'a@hotmail.com', first_name: 'Bugs', last_name: 'Bunny', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://clinamen.jamesjbrownjr.net/wp-content/uploads/2010/11/hacker.jpg' })

h2 = Hacker.create({ address: '35 rue Popincourt, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'b@hotmail.com', first_name: 'Daffy', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://clinamen.jamesjbrownjr.net/wp-content/uploads/2010/11/hacker.jpg' })

h3 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'c@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://clinamen.jamesjbrownjr.net/wp-content/uploads/2010/11/hacker.jpg' })

h4 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'd@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://clinamen.jamesjbrownjr.net/wp-content/uploads/2010/11/hacker.jpg' })

h5 = Hacker.create({ address: '180 Lisson Grove, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'e@hotmail.com', first_name: 'Donald', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://clinamen.jamesjbrownjr.net/wp-content/uploads/2010/11/hacker.jpg' })