Hacker.delete_all

h1 = Hacker.create({ address: '32 Bowling Green Lane, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'a@hotmail.com', first_name: 'Bugs', last_name: 'Bunny', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://si0.twimg.com/profile_images/1804619855/hangover-alan.jpg' })

h2 = Hacker.create({ address: '35 rue Popincourt, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'b@hotmail.com', first_name: 'Daffy', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://si0.twimg.com/profile_images/1956916230/profile_eq_sq.png' })

h3 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'c@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://a1.twimg.com/profile_images/1260561868/twitter-profile-pic.jpg' })

h4 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'd@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://si0.twimg.com/profile_images/3437045197/0c0ade4ce63dafb72fa2b93296b985d7.jpeg' })

h5 = Hacker.create({ address: '180 Lisson Grove, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'e@hotmail.com', first_name: 'Donald', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://a0.twimg.com/profile_images/1844906295/DSC_0255.jpg' })

h6 = Hacker.create({ address: '180 Lisson Grove, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'f@hotmail.com', first_name: 'Donald', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://twimg0-a.akamaihd.net/profile_images/2327068026/image.jpg' })

h7 = Hacker.create({ address: '32 Bowling Green Lane, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'g@hotmail.com', first_name: 'Bugs', last_name: 'Bunny', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://a3.twimg.com/profile_images/1209855600/2010Dec26_2787.JPG' })

h8 = Hacker.create({ address: '35 rue Popincourt, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'h@hotmail.com', first_name: 'Daffy', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://si0.twimg.com/profile_images/2197727437/IMG_1561.JPG' })

h9 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'i@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://media-cache-ec1.pinimg.com/avatars/jpcote-62_600.jpg' })

h10 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'j@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://si0.twimg.com/profile_images/1332549533/stevej_ded_profile.jpg' })

h11 = Hacker.create({ address: '180 Lisson Grove, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'k@hotmail.com', first_name: 'Donald', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://si0.twimg.com/profile_images/3439826468/f1982d63bcd43cba9885e2beb46878d8.jpeg' })

h12 = Hacker.create({ address: '32 Bowling Green Lane, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'l@hotmail.com', first_name: 'Bugs', last_name: 'Bunny', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://si0.twimg.com/profile_images/1417494976/IMG_0307.JPG' })

h13 = Hacker.create({ address: '35 rue Popincourt, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'm@hotmail.com', first_name: 'Daffy', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://twimg0-a.akamaihd.net/profile_images/2551161665/image.jpg' })

h14 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'n@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://a0.twimg.com/profile_images/1221111435/Kevin_Poulsen_11.jpg' })

h15 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'o@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://nyobetabeat.files.wordpress.com/2012/06/grouper-michael-waxman.jpg' })

h16 = Hacker.create({ address: '180 Lisson Grove, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'p@hotmail.com', first_name: 'Donald', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://boygeniusreport.files.wordpress.com/2011/08/topiary110801145506.jpg?w=942' })

h17 = Hacker.create({ address: '32 Bowling Green Lane, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'q@hotmail.com', first_name: 'Bugs', last_name: 'Bunny', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://a2.twimg.com/profile_images/1623213093/image.jpg' })

h18 = Hacker.create({ address: '35 rue Popincourt, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'r@hotmail.com', first_name: 'Daffy', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://cdn0.dailydot.com/uploaded/images/original/2013/4/10/Queen_Anonymous.jpg' })

h19 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 's@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://www.bitrebels.com/wp-content/uploads/2013/01/sam-applegate-seo-expert-3.jpg' })

h20 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 't@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://a0.twimg.com/profile_images/2815353846/c833065ca63da9b4fecc65dd4b0d5351.jpeg' })

h21 = Hacker.create({ address: '35 rue Popincourt, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'u@hotmail.com', first_name: 'Daffy', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://media.tumblr.com/tumblr_lqjm1uPG7f1qjfwo1.jpg' })

h22 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'v@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://media-cache-ec3.pinimg.com/avatars/sarahjfenn-16_600.jpg' })

h23 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'w@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://i1.sndcdn.com/artworks-000039383883-irs4ae-original.jpg?de05208' })

h24 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'x@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://a0.twimg.com/profile_images/663989083/icon.jpg' })

h25 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'y@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://twimg0-a.akamaihd.net/profile_images/2119333116/380692_875858969786_34507820_37123534_1097304424_n.jpg' })

h26 = Hacker.create({ address: '35 rue Popincourt, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'z@hotmail.com', first_name: 'Daffy', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://www.eriereader.com/uploads/photos/l/Hacker_1368585964.jpg' })

h27 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'aa@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://www.letstravelsomewhere.com/wp-content/uploads/2013/01/lets-travel-with-michael-hacker.jpg' })

h28 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'ab@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://i1.sndcdn.com/avatars-000030900893-sit122-t500x500.jpg?6462778' })

h29 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'ac@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://clatl.com/imager/stieg-larssons-hacker-heroine-makes-heads-spin/b/original/1581830/f0cc/arts_feature1-2_10.jpg' })

h30 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'ad@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://twimg0-a.akamaihd.net/profile_images/2548790849/ywyjnfa2hm5ukwt13iow.jpeg' })

h31 = Hacker.create({ address: '35 rue Popincourt, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'ae@hotmail.com', first_name: 'Daffy', last_name: 'Duck', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'https://twimg0-a.akamaihd.net/profile_images/2704323274/8a2b8e0e8049f6986a4aa238615875a7.jpeg' })

h32 = Hacker.create({ address: '9 Back Hill, London, United Kingdom', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'af@hotmail.com', first_name: 'Elmer', last_name: 'Fudd', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://farm3.static.flickr.com/2453/4043610341_654a1fec88.jpg' })

h33 = Hacker.create({ address: '20 Boulevard Voltaire, Paris, France', current_projects: 'Facebook clone, Twilio extension, SMS iOS system', email: 'ag@hotmail.com', first_name: 'Pepe', last_name: 'Lepeau', git_url: 'http://www.github.com/ubersapiens', objectives: 'To create small web consultancy firm that specialises in digital solutions that have social impact.', password_confirmation: '12345', password: '12345', best_project: 'http://urbanmonkey.herokuapp.com', portfolio_url: 'http://www.lightbulbmanifesto.com', stack: 'HTML5, CSS3, JavaScript, Ruby, Rails, Backbone.js, Git', twitter_url: 'http://www.twitter.com/jfp_3', avatar_url: 'http://a0.twimg.com/profile_images/2598761992/q0sbzih8m23gclnxs58g.jpeg' })

